site_name: Minecraft

repo_name: '2024.1-Minecraft'
repo_url: 'https://github.com/SBD1/2024.1-Minecraft'

docs_dir: gitpages/docs

theme:
  name: material
  language: pt-BR
  font: 
    text: Roboto
  logo: assets/icons/favicon.svg
  favicon: assets/icons/favicon.svg
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Modo Escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-3
        name: Modo Claro

nav: 
  - Início: index.md
  - Apresentações: apresentacoes.md
  - Módulo 1 - Modelagem:
    - Diagrama Entidade-Relacionamento: modulo_1/der.md
    - Modelo Relacional: modulo_1/modeloRelacional.md
    - Dicionário de Dados: modulo_1/dicDados.md
  # - Módulo 2 - SQL:
  # - Módulo 3 - Transactions, Triggers e Stored Procedures:

# extra_css:
#   - css/custom.css

# extra_javascript:
#   - js/custom.js