version: '27.0.3'
services:
  db:
    build:
      context: ../db
      dockerfile: Dockerfile.db
    container_name: 2024_1_Minecraft
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 2024_1_Minecraft
    ports:
      - "5432:5432"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    container_name: python_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/2024_1_Minecraft
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    # command: >
    #   sh -c './wait-for-it.sh db:5432 -- python main.py'

volumes:
  db_data:
